spring:
    application:
        name: basketball-stats-spring
    datasource:
        url: jdbc:mysql://kawoobase.cnsi2a4g0yx0.eu-central-1.rds.amazonaws.com/bbstats
        username: root
        password: MyRoot24#
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            show-sql: true
        open-in-view: false
    devtools:
        restart:
            quiet-period: 900
server:
    port: 8081
    servlet:
        context-path: /rest
